version: "3.8"

networks:
  default:
    name: foulbot

services:
  foulbot:
    image: ${DOCKER_REGISTRY-}foulbot
    container_name: foulbot
    build:
      context: .
      dockerfile: FoulBot.Api/Dockerfile
    restart: unless-stopped
    mem_limit: 400m
    mem_reservation: 300m
    env_file:
      - secrets.env
    volumes:
      - ./key.json:/app/key.json
