version: "3.8"

networks:
  default:
    name: foulbot

services:
  foulbot:
    image: ${DOCKER_REGISTRY-}foulbot
    container_name: foulbot
    build:
      context: .
      dockerfile: FoulBot.Api/Dockerfile
    restart: unless-stopped
    mem_limit: 400m
    mem_reservation: 300m
    env_file:
      - secrets.env
    volumes:
      - ./key.json:/app/key.json
      #- ./chats:/app/chats # For some reason it doesn't work, something with linux permissions.
      - /data/foulbot-logs:/app/logs

  #seq:
  #  image: datalust/seq:latest
  #  container_name: foulbot-seq
  #  restart: unless-stopped
  #  mem_limit: 800m
  #  mem_reservation: 400m
  #  environment:
  #    - ACCEPT_EULA=Y
  #  ports:
  #    - 8081:80
  #  volumes:
  #    - /data/foulbot-seq:/data
